### ISSUE TITLE
Compilation error on Xcode 14.3 beta

### ISSUE THREAD

**Issue by crayment** [GetStream/stream-chat-swiftui#287]
## What did you do?
Try to compile on Xcode 14.3 beta 2

## What did you expect to happen?
Compile to succeeed

## What happened instead?
Got this error:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/78082/223803889-87361387-2593-4a98-b2a7-407af588995d.png">

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.4
**Swift version:** 5.7
**Xcode version:** 14.3 beta 2
**Device:** iPad Pro (11-inch) 4th generation

## Additional context

I can't believe this ever worked 🙃

**Comment by martinmitrevski** [comment]
Hi @crayment,

Thanks for bringing this up, it's fixed now. 

Best, Martin
